import {
  AlertCircleIcon,
  ArchiveIcon,
  AwardIcon,
  BellIcon,
  BoltIcon,
  BookmarkIcon,
  BookOpenIcon,
  BoxIcon,
  BriefcaseIcon,
  BugIcon,
  CalendarIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleIcon,
  CircleOffIcon,
  ClockIcon,
  ClockArrowDownIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  EditIcon,
  EyeIcon,
  FeatherIcon,
  FileIcon,
  FilmIcon,
  FlagIcon,
  FlameIcon,
  FlaskConicalIcon,
  FolderIcon,
  GiftIcon,
  GlobeIcon,
  GridIcon,
  HashIcon,
  HeadphonesIcon,
  HeartIcon,
  HexagonIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  KeyIcon,
  LayersIcon,
  LayoutIcon,
  LightbulbIcon,
  LinkIcon,
  ListIcon,
  LoaderIcon,
  LockIcon,
  MailIcon,
  MapIcon,
  MapPinIcon,
  MessageCircleIcon,
  MicIcon,
  MonitorIcon,
  MoonIcon,
  MusicIcon,
  PackageIcon,
  PaperclipIcon,
  PauseIcon,
  PenIcon,
  PercentIcon,
  PhoneIcon,
  PieChartIcon,
  PinIcon,
  PlayIcon,
  PlusIcon,
  PocketIcon,
  PowerIcon,
  PrinterIcon,
  RadioIcon,
  RefreshCwIcon,
  RocketIcon,
  RssIcon,
  SaveIcon,
  ScissorsIcon,
  SearchIcon,
  SendIcon,
  ServerIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SidebarIcon,
  SkipForwardIcon,
  SlidersIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  SpeakerIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TableIcon,
  TabletIcon,
  TagIcon,
  TargetIcon,
  TerminalIcon,
  ThermometerIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  ToggleLeftIcon,
  Trash2Icon,
  TrashIcon,
  TrendingUpIcon,
  TriangleIcon,
  TruckIcon,
  TvIcon,
  TypeIcon,
  UmbrellaIcon,
  UnderlineIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  VoicemailIcon,
  VolumeIcon,
  WatchIcon,
  WifiIcon,
  WindIcon,
  WrenchIcon,
  XIcon,
  ZapIcon,
  ZoomInIcon,
} from "lucide-react";
import React from "react";

/**
 * Type for a Lucide icon component with optional className and style props.
 */
export type LucideIconComponent = React.ComponentType<{
  className?: string;
  style?: React.CSSProperties;
}>;

/**
 * Static map from kebab-case icon names to Lucide icon components.
 * Covers all icons in the stage + label SUGGESTED_ICONS pickers.
 * Unknown names fall back to CircleIcon.
 */
const ICON_MAP: Record<string, LucideIconComponent> = {
  "alert-circle": AlertCircleIcon,
  archive: ArchiveIcon,
  award: AwardIcon,
  bell: BellIcon,
  bolt: BoltIcon,
  "book-open": BookOpenIcon,
  bookmark: BookmarkIcon,
  box: BoxIcon,
  briefcase: BriefcaseIcon,
  bug: BugIcon,
  calendar: CalendarIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  circle: CircleIcon,
  "circle-off": CircleOffIcon,
  clock: ClockIcon,
  "clock-arrow-down": ClockArrowDownIcon,
  cloud: CloudIcon,
  code: CodeIcon,
  coffee: CoffeeIcon,
  compass: CompassIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  edit: EditIcon,
  eye: EyeIcon,
  feather: FeatherIcon,
  file: FileIcon,
  film: FilmIcon,
  flag: FlagIcon,
  flame: FlameIcon,
  "flask-conical": FlaskConicalIcon,
  folder: FolderIcon,
  gift: GiftIcon,
  globe: GlobeIcon,
  grid: GridIcon,
  hash: HashIcon,
  headphones: HeadphonesIcon,
  heart: HeartIcon,
  hexagon: HexagonIcon,
  home: HomeIcon,
  image: ImageIcon,
  inbox: InboxIcon,
  key: KeyIcon,
  layers: LayersIcon,
  layout: LayoutIcon,
  lightbulb: LightbulbIcon,
  link: LinkIcon,
  list: ListIcon,
  loader: LoaderIcon,
  lock: LockIcon,
  mail: MailIcon,
  map: MapIcon,
  "map-pin": MapPinIcon,
  "message-circle": MessageCircleIcon,
  mic: MicIcon,
  monitor: MonitorIcon,
  moon: MoonIcon,
  music: MusicIcon,
  package: PackageIcon,
  paperclip: PaperclipIcon,
  pause: PauseIcon,
  pen: PenIcon,
  percent: PercentIcon,
  phone: PhoneIcon,
  "pie-chart": PieChartIcon,
  pin: PinIcon,
  play: PlayIcon,
  plus: PlusIcon,
  pocket: PocketIcon,
  power: PowerIcon,
  printer: PrinterIcon,
  radio: RadioIcon,
  "refresh-cw": RefreshCwIcon,
  rocket: RocketIcon,
  rss: RssIcon,
  save: SaveIcon,
  scissors: ScissorsIcon,
  search: SearchIcon,
  send: SendIcon,
  server: ServerIcon,
  settings: SettingsIcon,
  share: ShareIcon,
  shield: ShieldIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  sidebar: SidebarIcon,
  "skip-forward": SkipForwardIcon,
  sliders: SlidersIcon,
  smartphone: SmartphoneIcon,
  smile: SmileIcon,
  sparkles: SparklesIcon,
  speaker: SpeakerIcon,
  square: SquareIcon,
  star: StarIcon,
  sun: SunIcon,
  table: TableIcon,
  tablet: TabletIcon,
  tag: TagIcon,
  target: TargetIcon,
  terminal: TerminalIcon,
  thermometer: ThermometerIcon,
  "thumbs-down": ThumbsDownIcon,
  "thumbs-up": ThumbsUpIcon,
  "toggle-left": ToggleLeftIcon,
  tool: WrenchIcon,
  trash: TrashIcon,
  "trash-2": Trash2Icon,
  "trending-up": TrendingUpIcon,
  triangle: TriangleIcon,
  truck: TruckIcon,
  tv: TvIcon,
  type: TypeIcon,
  umbrella: UmbrellaIcon,
  underline: UnderlineIcon,
  unlock: UnlockIcon,
  upload: UploadIcon,
  user: UserIcon,
  users: UsersIcon,
  video: VideoIcon,
  voicemail: VoicemailIcon,
  volume: VolumeIcon,
  watch: WatchIcon,
  wifi: WifiIcon,
  wind: WindIcon,
  wrench: WrenchIcon,
  x: XIcon,
  zap: ZapIcon,
  "zoom-in": ZoomInIcon,
};

/**
 * Retrieves a Lucide icon component by its kebab-case name.
 * Falls back to CircleIcon if the icon is not found in the map.
 */
export function getLucideIcon(iconName: string): LucideIconComponent {
  return ICON_MAP[iconName] ?? CircleIcon;
}

/**
 * Renders a stage icon by its kebab-case name.
 * Uses React.createElement to avoid "component created during render" lint errors.
 */
export function renderStageIcon(
  iconName: string,
  className?: string,
  style?: React.CSSProperties
): React.ReactElement {
  const IconComponent = getLucideIcon(iconName);
  return React.createElement(IconComponent, { className, style });
}
