import "server-only";

import { randomBytes, timingSafeEqual } from "crypto";

import { cookies } from "next/headers";

import { COOKIE_DOMAIN } from "./config";
import { signCookiePayload, verifySignedCookiePayload } from "./cookie-signing";

/**
 * CSRF Protection Module
 *
 * Provides Cross-Site Request Forgery protection for Server Actions.
 * Uses a signed double-submit cookie pattern with timing-safe comparison.
 *
 * Token lifecycle:
 * 1. The proxy bootstraps a signed CSRF cookie when none is present or the existing
 *    cookie fails signature/format checks (for example after rotating
 *    `HELVETY_COOKIE_SIGNING_SECRET`). It also forwards the plaintext token on
 *    `x-csrf-bootstrap-token` for the current request. `cookies().set()` is not
 *    allowed in Server Components or layouts and will throw at runtime.
 * 2. Layouts read the token via `getCachedCSRFToken` (validated cookie first, then
 *    the bootstrap header) and pass it to `CSRFProvider` for client components.
 * 3. Server Actions validate the token with validateCSRFToken() /
 *    requireCSRFToken().
 * 4. After auth state changes, mutating actions may call `generateCSRFToken()`
 *    and return the new plaintext token; clients apply it with `useSetCSRFToken`
 *    from `@helvety/ui/csrf-provider` before the next CSRF-protected action
 *    (auth OTP verify → passkey auto-start is the primary case).
 *
 * Read-only server actions that do not call `requireCSRFToken` still require an
 * authenticated session and should use `authenticateAndRateLimit` read-style
 * limits (see AGENTS.md and `@helvety/shared/action-helpers`).
 */

const CSRF_COOKIE_NAME = "csrf_token";
const CSRF_TOKEN_LENGTH = 32;

/**
 * Generate a new CSRF token and store it in an HttpOnly cookie.
 *
 * WARNING: This function calls cookies().set(), which is only allowed in
 * Server Actions, Route Handlers, and the proxy (proxy.ts). Do NOT call
 * this from Server Components or layouts -- it will throw at runtime.
 *
 * In practice, CSRF token generation is usually handled by the proxy bootstrap.
 * This function is kept for post-auth rotation in Server Actions or Route Handlers.
 *
 * @returns The generated CSRF token
 */
export async function generateCSRFToken(): Promise<string> {
  const token = randomBytes(CSRF_TOKEN_LENGTH).toString("hex");
  const signedToken = await signCookiePayload(token);
  const cookieStore = await cookies();

  cookieStore.set(CSRF_COOKIE_NAME, signedToken, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 60 * 60 * 24,
    ...(process.env.NODE_ENV === "production" && { domain: COOKIE_DOMAIN }),
  });

  return token;
}

/**
 * Validate a CSRF token against the stored cookie value.
 *
 * Uses timingSafeEqual for equal-length token comparison to reduce timing
 * leakage during CSRF validation.
 *
 * @param token - The token to validate (from form submission or header)
 * @returns true if the token is valid, false otherwise
 */
export async function validateCSRFToken(
  token: string | null | undefined
): Promise<boolean> {
  if (!token) {
    return false;
  }

  const cookieStore = await cookies();
  const cookieValue = cookieStore.get(CSRF_COOKIE_NAME)?.value;
  const cookieToken = await getCSRFTokenFromCookieValue(cookieValue);

  if (!cookieToken) {
    return false;
  }

  // Use timing-safe comparison for equal-length buffers
  try {
    const tokenBuffer = Buffer.from(token, "utf8");
    const cookieBuffer = Buffer.from(cookieToken, "utf8");

    // Buffers must be the same length for timingSafeEqual
    if (tokenBuffer.length !== cookieBuffer.length) {
      return false;
    }

    return timingSafeEqual(tokenBuffer, cookieBuffer);
  } catch {
    return false;
  }
}

/**
 * Extracts and verifies the signed CSRF cookie payload.
 *
 * Returns the unsigned token only when signature and token format are valid.
 */
export async function getCSRFTokenFromCookieValue(
  cookieValue: string | null | undefined
): Promise<string | null> {
  const unsignedToken = await verifySignedCookiePayload(cookieValue);
  if (!unsignedToken) {
    return null;
  }

  // Hex-encoded random bytes generated by generateCSRFToken/proxy.
  if (!/^[0-9a-f]{64}$/i.test(unsignedToken)) {
    return null;
  }

  return unsignedToken;
}

/**
 * Require a valid CSRF token or throw an error.
 *
 * Use this in Server Actions that modify state.
 *
 * @param token - The token to validate
 * @throws Error if the token is invalid
 */
export async function requireCSRFToken(
  token: string | null | undefined
): Promise<void> {
  const isValid = await validateCSRFToken(token);

  if (!isValid) {
    throw new Error("Invalid CSRF token");
  }
}
