import fs from "node:fs";
import path from "node:path";

const DISPLAY_TIME_ZONE = "Europe/Zurich";
const now = new Date();
const dateTimeParts = Object.fromEntries(
  new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
    timeZone: DISPLAY_TIME_ZONE,
  })
    .formatToParts(now)
    .map(({ type, value }) => [type, value])
);
const version = `Generated on ${dateTimeParts.day}.${dateTimeParts.month}.${dateTimeParts.year} at ${dateTimeParts.hour}:${dateTimeParts.minute}:${dateTimeParts.second} (${DISPLAY_TIME_ZONE})`;

const versionFileContent = `// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const VERSION = "${version}";
`;

const configDir = path.join(process.cwd(), "lib", "config");
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
}

const versionFilePath = path.join(configDir, "version.ts");
fs.writeFileSync(versionFilePath, versionFileContent, "utf8");

console.log(`Generated version: ${version}`);
